version: 2
updates:
  - package-ecosystem: npm
    directory: /zhulong
    schedule:
      interval: monthly
    groups:
      frontend-dependencies:
        patterns: ['*']
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      python-dependencies:
        patterns: ['*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
